// **********************************************************************
// Parsed By TarsParser(2.4.5), Generated By tars2node(20200707)
// TarsParser Maintained By <TARS> and tars2node Maintained By <superzheng>
// Generated from "EduOOV.tars" by Client Mode
// **********************************************************************

/* eslint-disable */

"use strict";

var assert    = require("assert");
var TarsStream = require("@tars/stream");
var TarsError  = require("@tars/rpc").error;

var _hasOwnProperty = Object.prototype.hasOwnProperty;
var _makeError = function (data, message, type) {
    var error = new Error(message || "");
    error.request = data.request;
    error.response = {
        "costtime" : data.request.costtime
    };
    if (type === TarsError.CLIENT.DECODE_ERROR) {
        error.name = "DECODE_ERROR";
        error.response.error = {
            "code" : type,
            "message" : message
        };
    } else {
        error.name = "RPC_ERROR";
        error.response.error = data.error;
    }
    return error;
};

var EDU = EDU || {};
module.exports.EDU = EDU;

EDU.EduOOVProxy = function () {
    this._name    = undefined;
    this._worker  = undefined;
};

EDU.EduOOVProxy.prototype.setTimeout = function (iTimeout) {
    this._worker.timeout = iTimeout;
};

EDU.EduOOVProxy.prototype.getTimeout = function () {
    return this._worker.timeout;
};

EDU.EduOOVProxy.prototype.setVersion = function (iVersion) {
    this._worker.version = iVersion;
};

EDU.EduOOVProxy.prototype.getVersion = function () {
    return this._worker.version;
};

EDU.E_OOV_RET_CODE = {
    "E_OOV_RET_CODE_OK" : 0,
    "E_OOV_RET_CODE_UNKOWN" : -1
};
EDU.E_OOV_RET_CODE._classname = "EDU.E_OOV_RET_CODE";
EDU.E_OOV_RET_CODE._write = function(os, tag, val) { return os.writeInt32(tag, val); };
EDU.E_OOV_RET_CODE._read  = function(is, tag, def) { return is.readInt32(tag, true, def); };

EDU.OOVItem = function() {
    this.sWord = "";
    this.vResult = new TarsStream.List(TarsStream.String);
    this._classname = "EDU.OOVItem";
};
EDU.OOVItem._classname = "EDU.OOVItem";
EDU.OOVItem._write = function (os, tag, value) { os.writeStruct(tag, value); };
EDU.OOVItem._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
EDU.OOVItem._readFrom = function (is) {
    var tmp = new EDU.OOVItem;
    tmp.sWord = is.readString(0, false, "");
    tmp.vResult = is.readList(1, false, TarsStream.List(TarsStream.String));
    return tmp;
};
EDU.OOVItem.prototype._writeTo = function (os) {
    os.writeString(0, this.sWord);
    os.writeList(1, this.vResult);
};
EDU.OOVItem.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
EDU.OOVItem.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
EDU.OOVItem.prototype.toObject = function() { 
    return {
        "sWord" : this.sWord,
        "vResult" : this.vResult.toObject()
    };
};
EDU.OOVItem.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "sWord") && (this.sWord = json.sWord);
    _hasOwnProperty.call(json, "vResult") && (this.vResult.readFromObject(json.vResult));
    return this;
};
EDU.OOVItem.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
EDU.OOVItem.new = function () {
    return new EDU.OOVItem();
};
EDU.OOVItem.create = function (is) {
    return EDU.OOVItem._readFrom(is);
};

EDU.ClusterItem = function() {
    this.sCenterRef = "";
    this.vStudents = new TarsStream.List(TarsStream.String);
    this._classname = "EDU.ClusterItem";
};
EDU.ClusterItem._classname = "EDU.ClusterItem";
EDU.ClusterItem._write = function (os, tag, value) { os.writeStruct(tag, value); };
EDU.ClusterItem._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
EDU.ClusterItem._readFrom = function (is) {
    var tmp = new EDU.ClusterItem;
    tmp.sCenterRef = is.readString(0, false, "");
    tmp.vStudents = is.readList(1, false, TarsStream.List(TarsStream.String));
    return tmp;
};
EDU.ClusterItem.prototype._writeTo = function (os) {
    os.writeString(0, this.sCenterRef);
    os.writeList(1, this.vStudents);
};
EDU.ClusterItem.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
EDU.ClusterItem.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
EDU.ClusterItem.prototype.toObject = function() { 
    return {
        "sCenterRef" : this.sCenterRef,
        "vStudents" : this.vStudents.toObject()
    };
};
EDU.ClusterItem.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "sCenterRef") && (this.sCenterRef = json.sCenterRef);
    _hasOwnProperty.call(json, "vStudents") && (this.vStudents.readFromObject(json.vStudents));
    return this;
};
EDU.ClusterItem.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
EDU.ClusterItem.new = function () {
    return new EDU.ClusterItem();
};
EDU.ClusterItem.create = function (is) {
    return EDU.ClusterItem._readFrom(is);
};

EDU.OOVReq = function() {
    this.sSessionId = "";
    this.vRefs = new TarsStream.List(TarsStream.String);
    this._classname = "EDU.OOVReq";
};
EDU.OOVReq._classname = "EDU.OOVReq";
EDU.OOVReq._write = function (os, tag, value) { os.writeStruct(tag, value); };
EDU.OOVReq._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
EDU.OOVReq._readFrom = function (is) {
    var tmp = new EDU.OOVReq;
    tmp.sSessionId = is.readString(0, false, "");
    tmp.vRefs = is.readList(1, false, TarsStream.List(TarsStream.String));
    return tmp;
};
EDU.OOVReq.prototype._writeTo = function (os) {
    os.writeString(0, this.sSessionId);
    os.writeList(1, this.vRefs);
};
EDU.OOVReq.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
EDU.OOVReq.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
EDU.OOVReq.prototype.toObject = function() { 
    return {
        "sSessionId" : this.sSessionId,
        "vRefs" : this.vRefs.toObject()
    };
};
EDU.OOVReq.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "sSessionId") && (this.sSessionId = json.sSessionId);
    _hasOwnProperty.call(json, "vRefs") && (this.vRefs.readFromObject(json.vRefs));
    return this;
};
EDU.OOVReq.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
EDU.OOVReq.new = function () {
    return new EDU.OOVReq();
};
EDU.OOVReq.create = function (is) {
    return EDU.OOVReq._readFrom(is);
};

EDU.OOVRsp = function() {
    this.iRet = 0;
    this.sSessionId = "";
    this.sErrMsg = "";
    this.vTransResult = new TarsStream.List(TarsStream.List(EDU.OOVItem));
    this.vPhoneResult = new TarsStream.List(TarsStream.List(EDU.OOVItem));
    this._classname = "EDU.OOVRsp";
};
EDU.OOVRsp._classname = "EDU.OOVRsp";
EDU.OOVRsp._write = function (os, tag, value) { os.writeStruct(tag, value); };
EDU.OOVRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
EDU.OOVRsp._readFrom = function (is) {
    var tmp = new EDU.OOVRsp;
    tmp.iRet = is.readInt32(0, false, 0);
    tmp.sSessionId = is.readString(1, false, "");
    tmp.sErrMsg = is.readString(2, false, "");
    tmp.vTransResult = is.readList(3, false, TarsStream.List(TarsStream.List(EDU.OOVItem)));
    tmp.vPhoneResult = is.readList(4, false, TarsStream.List(TarsStream.List(EDU.OOVItem)));
    return tmp;
};
EDU.OOVRsp.prototype._writeTo = function (os) {
    os.writeInt32(0, this.iRet);
    os.writeString(1, this.sSessionId);
    os.writeString(2, this.sErrMsg);
    os.writeList(3, this.vTransResult);
    os.writeList(4, this.vPhoneResult);
};
EDU.OOVRsp.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
EDU.OOVRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
EDU.OOVRsp.prototype.toObject = function() { 
    return {
        "iRet" : this.iRet,
        "sSessionId" : this.sSessionId,
        "sErrMsg" : this.sErrMsg,
        "vTransResult" : this.vTransResult.toObject(),
        "vPhoneResult" : this.vPhoneResult.toObject()
    };
};
EDU.OOVRsp.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "iRet") && (this.iRet = json.iRet);
    _hasOwnProperty.call(json, "sSessionId") && (this.sSessionId = json.sSessionId);
    _hasOwnProperty.call(json, "sErrMsg") && (this.sErrMsg = json.sErrMsg);
    _hasOwnProperty.call(json, "vTransResult") && (this.vTransResult.readFromObject(json.vTransResult));
    _hasOwnProperty.call(json, "vPhoneResult") && (this.vPhoneResult.readFromObject(json.vPhoneResult));
    return this;
};
EDU.OOVRsp.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
EDU.OOVRsp.new = function () {
    return new EDU.OOVRsp();
};
EDU.OOVRsp.create = function (is) {
    return EDU.OOVRsp._readFrom(is);
};

EDU.OOVTransRsp = function() {
    this.iRet = 0;
    this.sSessionId = "";
    this.sErrMsg = "";
    this.vTransResult = new TarsStream.List(TarsStream.List(EDU.OOVItem));
    this._classname = "EDU.OOVTransRsp";
};
EDU.OOVTransRsp._classname = "EDU.OOVTransRsp";
EDU.OOVTransRsp._write = function (os, tag, value) { os.writeStruct(tag, value); };
EDU.OOVTransRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
EDU.OOVTransRsp._readFrom = function (is) {
    var tmp = new EDU.OOVTransRsp;
    tmp.iRet = is.readInt32(0, false, 0);
    tmp.sSessionId = is.readString(1, false, "");
    tmp.sErrMsg = is.readString(2, false, "");
    tmp.vTransResult = is.readList(3, false, TarsStream.List(TarsStream.List(EDU.OOVItem)));
    return tmp;
};
EDU.OOVTransRsp.prototype._writeTo = function (os) {
    os.writeInt32(0, this.iRet);
    os.writeString(1, this.sSessionId);
    os.writeString(2, this.sErrMsg);
    os.writeList(3, this.vTransResult);
};
EDU.OOVTransRsp.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
EDU.OOVTransRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
EDU.OOVTransRsp.prototype.toObject = function() { 
    return {
        "iRet" : this.iRet,
        "sSessionId" : this.sSessionId,
        "sErrMsg" : this.sErrMsg,
        "vTransResult" : this.vTransResult.toObject()
    };
};
EDU.OOVTransRsp.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "iRet") && (this.iRet = json.iRet);
    _hasOwnProperty.call(json, "sSessionId") && (this.sSessionId = json.sSessionId);
    _hasOwnProperty.call(json, "sErrMsg") && (this.sErrMsg = json.sErrMsg);
    _hasOwnProperty.call(json, "vTransResult") && (this.vTransResult.readFromObject(json.vTransResult));
    return this;
};
EDU.OOVTransRsp.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
EDU.OOVTransRsp.new = function () {
    return new EDU.OOVTransRsp();
};
EDU.OOVTransRsp.create = function (is) {
    return EDU.OOVTransRsp._readFrom(is);
};

EDU.OOVPhoneRsp = function() {
    this.iRet = 0;
    this.sSessionId = "";
    this.sErrMsg = "";
    this.vPhoneResult = new TarsStream.List(TarsStream.List(EDU.OOVItem));
    this._classname = "EDU.OOVPhoneRsp";
};
EDU.OOVPhoneRsp._classname = "EDU.OOVPhoneRsp";
EDU.OOVPhoneRsp._write = function (os, tag, value) { os.writeStruct(tag, value); };
EDU.OOVPhoneRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
EDU.OOVPhoneRsp._readFrom = function (is) {
    var tmp = new EDU.OOVPhoneRsp;
    tmp.iRet = is.readInt32(0, false, 0);
    tmp.sSessionId = is.readString(1, false, "");
    tmp.sErrMsg = is.readString(2, false, "");
    tmp.vPhoneResult = is.readList(3, false, TarsStream.List(TarsStream.List(EDU.OOVItem)));
    return tmp;
};
EDU.OOVPhoneRsp.prototype._writeTo = function (os) {
    os.writeInt32(0, this.iRet);
    os.writeString(1, this.sSessionId);
    os.writeString(2, this.sErrMsg);
    os.writeList(3, this.vPhoneResult);
};
EDU.OOVPhoneRsp.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
EDU.OOVPhoneRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
EDU.OOVPhoneRsp.prototype.toObject = function() { 
    return {
        "iRet" : this.iRet,
        "sSessionId" : this.sSessionId,
        "sErrMsg" : this.sErrMsg,
        "vPhoneResult" : this.vPhoneResult.toObject()
    };
};
EDU.OOVPhoneRsp.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "iRet") && (this.iRet = json.iRet);
    _hasOwnProperty.call(json, "sSessionId") && (this.sSessionId = json.sSessionId);
    _hasOwnProperty.call(json, "sErrMsg") && (this.sErrMsg = json.sErrMsg);
    _hasOwnProperty.call(json, "vPhoneResult") && (this.vPhoneResult.readFromObject(json.vPhoneResult));
    return this;
};
EDU.OOVPhoneRsp.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
EDU.OOVPhoneRsp.new = function () {
    return new EDU.OOVPhoneRsp();
};
EDU.OOVPhoneRsp.create = function (is) {
    return EDU.OOVPhoneRsp._readFrom(is);
};

EDU.ClusterReq = function() {
    this.vRefs = new TarsStream.List(TarsStream.String);
    this.mData = new TarsStream.Map(TarsStream.String, TarsStream.String);
    this.kClusters = 0;
    this._classname = "EDU.ClusterReq";
};
EDU.ClusterReq._classname = "EDU.ClusterReq";
EDU.ClusterReq._write = function (os, tag, value) { os.writeStruct(tag, value); };
EDU.ClusterReq._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
EDU.ClusterReq._readFrom = function (is) {
    var tmp = new EDU.ClusterReq;
    tmp.vRefs = is.readList(0, false, TarsStream.List(TarsStream.String));
    tmp.mData = is.readMap(1, false, TarsStream.Map(TarsStream.String, TarsStream.String));
    tmp.kClusters = is.readInt32(2, false, 0);
    return tmp;
};
EDU.ClusterReq.prototype._writeTo = function (os) {
    os.writeList(0, this.vRefs);
    os.writeMap(1, this.mData);
    os.writeInt32(2, this.kClusters);
};
EDU.ClusterReq.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
EDU.ClusterReq.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
EDU.ClusterReq.prototype.toObject = function() { 
    return {
        "vRefs" : this.vRefs.toObject(),
        "mData" : this.mData.toObject(),
        "kClusters" : this.kClusters
    };
};
EDU.ClusterReq.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "vRefs") && (this.vRefs.readFromObject(json.vRefs));
    _hasOwnProperty.call(json, "mData") && (this.mData.readFromObject(json.mData));
    _hasOwnProperty.call(json, "kClusters") && (this.kClusters = json.kClusters);
    return this;
};
EDU.ClusterReq.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
EDU.ClusterReq.new = function () {
    return new EDU.ClusterReq();
};
EDU.ClusterReq.create = function (is) {
    return EDU.ClusterReq._readFrom(is);
};

EDU.ClusterRsp = function() {
    this.iRet = 0;
    this.sMsg = "";
    this.vItems = new TarsStream.List(EDU.ClusterItem);
    this._classname = "EDU.ClusterRsp";
};
EDU.ClusterRsp._classname = "EDU.ClusterRsp";
EDU.ClusterRsp._write = function (os, tag, value) { os.writeStruct(tag, value); };
EDU.ClusterRsp._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
EDU.ClusterRsp._readFrom = function (is) {
    var tmp = new EDU.ClusterRsp;
    tmp.iRet = is.readInt32(0, false, 0);
    tmp.sMsg = is.readString(1, false, "");
    tmp.vItems = is.readList(2, false, TarsStream.List(EDU.ClusterItem));
    return tmp;
};
EDU.ClusterRsp.prototype._writeTo = function (os) {
    os.writeInt32(0, this.iRet);
    os.writeString(1, this.sMsg);
    os.writeList(2, this.vItems);
};
EDU.ClusterRsp.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
EDU.ClusterRsp.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
EDU.ClusterRsp.prototype.toObject = function() { 
    return {
        "iRet" : this.iRet,
        "sMsg" : this.sMsg,
        "vItems" : this.vItems.toObject()
    };
};
EDU.ClusterRsp.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "iRet") && (this.iRet = json.iRet);
    _hasOwnProperty.call(json, "sMsg") && (this.sMsg = json.sMsg);
    _hasOwnProperty.call(json, "vItems") && (this.vItems.readFromObject(json.vItems));
    return this;
};
EDU.ClusterRsp.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
EDU.ClusterRsp.new = function () {
    return new EDU.ClusterRsp();
};
EDU.ClusterRsp.create = function (is) {
    return EDU.ClusterRsp._readFrom(is);
};

var __EDU_EduOOV$getOOVPhone$IF = {
    "name" : "getOOVPhone",
    "return" : "int32",
    "arguments" : [{
        "name" : "stReq",
        "class" : "EDU.OOVReq",
        "direction" : "in"
    }, {
        "name" : "stRsp",
        "class" : "EDU.OOVPhoneRsp",
        "direction" : "out"
    }]
};

var __EDU_EduOOV$getOOVPhone$IE = function (stReq) {
    var os = new TarsStream.TarsOutputStream();
    os.writeStruct(1, stReq);
    return os.getBinBuffer();
};

var __EDU_EduOOV$getOOVPhone$ID = function (data) {
    try {
        var is = new TarsStream.TarsInputStream(data.response.sBuffer);
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : is.readInt32(0, true, 0),
                "arguments" : {
                    "stRsp" : is.readStruct(2, true, EDU.OOVPhoneRsp)
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __EDU_EduOOV$getOOVPhone$PE = function (stReq, __$PROTOCOL$VERSION) {
    var tup = new TarsStream.UniAttribute();
    tup.tupVersion = __$PROTOCOL$VERSION;
    tup.writeStruct("stReq", stReq);
    return tup;
};

var __EDU_EduOOV$getOOVPhone$PD = function (data) {
    try {
        var tup = data.response.tup;
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : tup.readInt32("", 0),
                "arguments" : {
                    "stRsp" : tup.readStruct("stRsp", EDU.OOVPhoneRsp)
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __EDU_EduOOV$getOOVPhone$ER = function (data) {
    throw _makeError(data, "Call EduOOV::getOOVPhone failed");
};

EDU.EduOOVProxy.prototype.getOOVPhone = function (stReq) {
    var version = this._worker.version;
    if (version === TarsStream.Tup.TUP_SIMPLE || version === TarsStream.Tup.TUP_COMPLEX) {
        return this._worker.tup_invoke("getOOVPhone", __EDU_EduOOV$getOOVPhone$PE(stReq, version), arguments[arguments.length - 1], __EDU_EduOOV$getOOVPhone$IF).then(__EDU_EduOOV$getOOVPhone$PD, __EDU_EduOOV$getOOVPhone$ER);
    } else {
        return this._worker.tars_invoke("getOOVPhone", __EDU_EduOOV$getOOVPhone$IE(stReq), arguments[arguments.length - 1], __EDU_EduOOV$getOOVPhone$IF).then(__EDU_EduOOV$getOOVPhone$ID, __EDU_EduOOV$getOOVPhone$ER);
    }
};
EDU.EduOOVProxy.getOOVPhone = __EDU_EduOOV$getOOVPhone$IF;

var __EDU_EduOOV$getOOVTotal$IF = {
    "name" : "getOOVTotal",
    "return" : "int32",
    "arguments" : [{
        "name" : "stReq",
        "class" : "EDU.OOVReq",
        "direction" : "in"
    }, {
        "name" : "stRsp",
        "class" : "EDU.OOVRsp",
        "direction" : "out"
    }]
};

var __EDU_EduOOV$getOOVTotal$IE = function (stReq) {
    var os = new TarsStream.TarsOutputStream();
    os.writeStruct(1, stReq);
    return os.getBinBuffer();
};

var __EDU_EduOOV$getOOVTotal$ID = function (data) {
    try {
        var is = new TarsStream.TarsInputStream(data.response.sBuffer);
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : is.readInt32(0, true, 0),
                "arguments" : {
                    "stRsp" : is.readStruct(2, true, EDU.OOVRsp)
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __EDU_EduOOV$getOOVTotal$PE = function (stReq, __$PROTOCOL$VERSION) {
    var tup = new TarsStream.UniAttribute();
    tup.tupVersion = __$PROTOCOL$VERSION;
    tup.writeStruct("stReq", stReq);
    return tup;
};

var __EDU_EduOOV$getOOVTotal$PD = function (data) {
    try {
        var tup = data.response.tup;
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : tup.readInt32("", 0),
                "arguments" : {
                    "stRsp" : tup.readStruct("stRsp", EDU.OOVRsp)
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __EDU_EduOOV$getOOVTotal$ER = function (data) {
    throw _makeError(data, "Call EduOOV::getOOVTotal failed");
};

EDU.EduOOVProxy.prototype.getOOVTotal = function (stReq) {
    var version = this._worker.version;
    if (version === TarsStream.Tup.TUP_SIMPLE || version === TarsStream.Tup.TUP_COMPLEX) {
        return this._worker.tup_invoke("getOOVTotal", __EDU_EduOOV$getOOVTotal$PE(stReq, version), arguments[arguments.length - 1], __EDU_EduOOV$getOOVTotal$IF).then(__EDU_EduOOV$getOOVTotal$PD, __EDU_EduOOV$getOOVTotal$ER);
    } else {
        return this._worker.tars_invoke("getOOVTotal", __EDU_EduOOV$getOOVTotal$IE(stReq), arguments[arguments.length - 1], __EDU_EduOOV$getOOVTotal$IF).then(__EDU_EduOOV$getOOVTotal$ID, __EDU_EduOOV$getOOVTotal$ER);
    }
};
EDU.EduOOVProxy.getOOVTotal = __EDU_EduOOV$getOOVTotal$IF;

var __EDU_EduOOV$getOOVTrans$IF = {
    "name" : "getOOVTrans",
    "return" : "int32",
    "arguments" : [{
        "name" : "stReq",
        "class" : "EDU.OOVReq",
        "direction" : "in"
    }, {
        "name" : "stRsp",
        "class" : "EDU.OOVTransRsp",
        "direction" : "out"
    }]
};

var __EDU_EduOOV$getOOVTrans$IE = function (stReq) {
    var os = new TarsStream.TarsOutputStream();
    os.writeStruct(1, stReq);
    return os.getBinBuffer();
};

var __EDU_EduOOV$getOOVTrans$ID = function (data) {
    try {
        var is = new TarsStream.TarsInputStream(data.response.sBuffer);
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : is.readInt32(0, true, 0),
                "arguments" : {
                    "stRsp" : is.readStruct(2, true, EDU.OOVTransRsp)
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __EDU_EduOOV$getOOVTrans$PE = function (stReq, __$PROTOCOL$VERSION) {
    var tup = new TarsStream.UniAttribute();
    tup.tupVersion = __$PROTOCOL$VERSION;
    tup.writeStruct("stReq", stReq);
    return tup;
};

var __EDU_EduOOV$getOOVTrans$PD = function (data) {
    try {
        var tup = data.response.tup;
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : tup.readInt32("", 0),
                "arguments" : {
                    "stRsp" : tup.readStruct("stRsp", EDU.OOVTransRsp)
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __EDU_EduOOV$getOOVTrans$ER = function (data) {
    throw _makeError(data, "Call EduOOV::getOOVTrans failed");
};

EDU.EduOOVProxy.prototype.getOOVTrans = function (stReq) {
    var version = this._worker.version;
    if (version === TarsStream.Tup.TUP_SIMPLE || version === TarsStream.Tup.TUP_COMPLEX) {
        return this._worker.tup_invoke("getOOVTrans", __EDU_EduOOV$getOOVTrans$PE(stReq, version), arguments[arguments.length - 1], __EDU_EduOOV$getOOVTrans$IF).then(__EDU_EduOOV$getOOVTrans$PD, __EDU_EduOOV$getOOVTrans$ER);
    } else {
        return this._worker.tars_invoke("getOOVTrans", __EDU_EduOOV$getOOVTrans$IE(stReq), arguments[arguments.length - 1], __EDU_EduOOV$getOOVTrans$IF).then(__EDU_EduOOV$getOOVTrans$ID, __EDU_EduOOV$getOOVTrans$ER);
    }
};
EDU.EduOOVProxy.getOOVTrans = __EDU_EduOOV$getOOVTrans$IF;

var __EDU_EduOOV$textCluster$IF = {
    "name" : "textCluster",
    "return" : "int32",
    "arguments" : [{
        "name" : "stReq",
        "class" : "EDU.ClusterReq",
        "direction" : "in"
    }, {
        "name" : "stRsp",
        "class" : "EDU.ClusterRsp",
        "direction" : "out"
    }]
};

var __EDU_EduOOV$textCluster$IE = function (stReq) {
    var os = new TarsStream.TarsOutputStream();
    os.writeStruct(1, stReq);
    return os.getBinBuffer();
};

var __EDU_EduOOV$textCluster$ID = function (data) {
    try {
        var is = new TarsStream.TarsInputStream(data.response.sBuffer);
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : is.readInt32(0, true, 0),
                "arguments" : {
                    "stRsp" : is.readStruct(2, true, EDU.ClusterRsp)
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __EDU_EduOOV$textCluster$PE = function (stReq, __$PROTOCOL$VERSION) {
    var tup = new TarsStream.UniAttribute();
    tup.tupVersion = __$PROTOCOL$VERSION;
    tup.writeStruct("stReq", stReq);
    return tup;
};

var __EDU_EduOOV$textCluster$PD = function (data) {
    try {
        var tup = data.response.tup;
        return {
            "request" : data.request,
            "response" : {
                "costtime" : data.request.costtime,
                "return" : tup.readInt32("", 0),
                "arguments" : {
                    "stRsp" : tup.readStruct("stRsp", EDU.ClusterRsp)
                }
            }
        };
    } catch (e) {
        throw _makeError(data, e.message, TarsError.CLIENT.DECODE_ERROR);
    }
};

var __EDU_EduOOV$textCluster$ER = function (data) {
    throw _makeError(data, "Call EduOOV::textCluster failed");
};

EDU.EduOOVProxy.prototype.textCluster = function (stReq) {
    var version = this._worker.version;
    if (version === TarsStream.Tup.TUP_SIMPLE || version === TarsStream.Tup.TUP_COMPLEX) {
        return this._worker.tup_invoke("textCluster", __EDU_EduOOV$textCluster$PE(stReq, version), arguments[arguments.length - 1], __EDU_EduOOV$textCluster$IF).then(__EDU_EduOOV$textCluster$PD, __EDU_EduOOV$textCluster$ER);
    } else {
        return this._worker.tars_invoke("textCluster", __EDU_EduOOV$textCluster$IE(stReq), arguments[arguments.length - 1], __EDU_EduOOV$textCluster$IF).then(__EDU_EduOOV$textCluster$ID, __EDU_EduOOV$textCluster$ER);
    }
};
EDU.EduOOVProxy.textCluster = __EDU_EduOOV$textCluster$IF;



